### ISSUE TITLE
Wrong regressor values

### ISSUE THREAD

**Issue by Zumbalamambo** [tkwoo/segmentation_open#2]
I guess the color values are wrong. Correct me if Im mistaken

```
    def make_regressor_label(self, gt):
        human = np.where(gt==24,255,0) + np.where(gt==25,255,0)
        car = np.where(gt==26,255,0) + np.where(gt==27,255,0) + np.where(gt==28,20,0)
        road = np.where(gt==7,255,0) #+ np.where(gt==8,1,0)
        label = np.concatenate((human, car, road), axis=-1)

        return label
```

The color code for the human in the segmentation mask is #181818 which in rgb is (24,24,24) but we are searching   for wrong values between (24,255,0) and (24,255,0). why so?

**Comment by tkwoo** [comment]
Label image is represented to gray scale, not 3ch rgb color.
Label : 24(pedestrian), 25(cyclist)
I changed label into a sparse matrix for making ground truth. so 24, 25 -> 255

    if gt[idx]==24 or gt[idx]==25:
     human[idx] = 255
    else:
     human[idx] = 0

**Comment by Zumbalamambo** [comment]
![20170905094129778](https://user-images.githubusercontent.com/24539006/38190563-673100a0-3697-11e8-8339-ded4a6cade9d.png)


This is how the groundtruth image will be incase if I photoshop it.
However the groundtruth image that you've provided looks bit different... May I know how do did you generate them?

**Comment by Zumbalamambo** [comment]
I have got one more doubt...

How do we get the label as 24,25? is it hardcoded value based on cityscape dataset?

**Comment by tkwoo** [comment]
@Zumbalamambo cityscape provide with 2 types groundtruth, one is color type, another is grayscale.
Check original GT parser
https://github.molgen.mpg.de/mohomran/cityscapes/blob/682adf38b69bdf858bed556796638a5a78f1c762/scripts/helpers/labels.py#L56

    Label(  'person'               , 24 ,       11 , 'human'           , 6       , True         , False        , (220, 20, 60) ),
    Label(  'rider'                , 25 ,       12 , 'human'           , 6       , True         , False        , (255,  0,  0) ),

**Comment by Zumbalamambo** [comment]
@tkwoo Thank you. If i have to train on my own dataset, how the make_regressor_label should be? I used the grayscale and the accuracy is bit low. Will it improve if I use rgb?

**Comment by tkwoo** [comment]
@Zumbalamambo How many do you prepare the training images? In this project, I used 3750 rgb images and Unet, valdiation quality was quite reasonable.(I checked qualitatively)

**Comment by Zumbalamambo** [comment]
i have used 1000 images....I will increase the dataset. Can you please tell me how i need to change the make_regressor_label label function if I have to train more than three class ?

**Comment by enomto** [comment]
Could you tell me the attributes of the 3750 images? Also, I'm worried about how to design labels etc. Although I am rewriting, there may be something that goes wrong occasionally, so I may understand something.

**Comment by tkwoo** [comment]
@enomto 
I rescaled cityscape image into 1/4 size for fast training. (1024, 2048, 3) --> (256, 512, 3)
Feel free to modify input size.

**Comment by Zumbalamambo** [comment]
@tkwoo Thank you. I will try with the new code and will update ...

**Comment by Zumbalamambo** [comment]
I have set the width to 1920 and height to 1080. But Im getting the following error,


> ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 134, 240, 256), (None, 135, 240, 256)]


How do I sort it out?

**Comment by Zumbalamambo** [comment]
@tkwoo how do I choose the input shape?
