### ISSUE TITLE
About predict.py

### ISSUE THREAD

**Issue by enomto** [tkwoo/segmentation_open#3]
This visualization tool is interesting.
I would like to ask you
What is specified for the test image format etc?
ｐredict.py can not be executed due to an error.

 input_data = imgInput.reshape((1,256,256,1))
AttributeError: 'NoneType' object has no attribute 'reshape'

I am adjusting the image conditions, but what do you suppose to do with formats and image matrices?

**Comment by tkwoo** [comment]
@enomto 
Sorry, I forgot about updating prediction code.
https://github.com/tkwoo/visualization-segmentation-process/commit/7b2e9b367a2cbe31f8d29b9646c90ce410a2a58f

After training, 

``` python main.py --mode predict_img ```

**Comment by tkwoo** [comment]
The model used in this project has `(None, 256, 512, 3)` tensor.

**Comment by enomto** [comment]
Ok! thank you
